version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: pizza-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: myzaa
      MYSQL_DATABASE: pizza
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --general-log=1
      - --log-output=TABLE

volumes:
  mysql_data:

